name: 'Generate STL Files'
description: 'Generate STL files from all SCAD files in the repository'
outputs:
  stl-files:
    description: 'List of generated STL files'
    value: ${{ steps.generate.outputs.stl-files }}
runs:
  using: 'composite'
  steps:
    - name: Find SCAD files
      shell: bash
      id: find-scad
      run: |
        find . -name "*.scad" -type f | head -20 > scad_files.txt
        echo "files<<EOF" >> $GITHUB_OUTPUT
        cat scad_files.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Generate STL files
      shell: bash
      id: generate
      run: |
        mkdir -p stl_output
        stl_files=""
        while IFS= read -r scad_file; do
          if [ -n "$scad_file" ]; then
            base_name=$(basename "$scad_file" .scad)
            stl_path="stl_output/${base_name}.stl"
            echo "Processing: $scad_file -> $stl_path"
            xvfb-run -a openscad -o "$stl_path" "$scad_file"
            if [ -f "$stl_path" ]; then
              stl_files="$stl_files$stl_path "
            fi
          fi
        done < scad_files.txt
        echo "stl-files=$stl_files" >> $GITHUB_OUTPUT