name: 'Create PR Comment with Previews'
description: 'Create or update a PR comment with preview image links'
inputs:
  preview-files:
    description: 'Space-separated list of preview image files'
    required: true
  file-list:
    description: 'Space-separated list of file basenames'
    required: false
  pr-number:
    description: 'Pull request number'
    required: true
  github-token:
    description: 'GitHub token for commenting'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate preview comment body
      shell: bash
      id: preview-comment
      run: |
        echo "comment-body<<EOF" >> $GITHUB_OUTPUT
        echo "## ðŸŽ² OpenSCAD Preview Images" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Generated preview images for this PR:" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        
        # Get repository info for GitHub Pages URL
        repo_owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        pages_base_url="https://${repo_owner}.github.io/${repo_name}"
        artifact_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        for preview_file in ${{ inputs.preview-files }}; do
          if [ -f "$preview_file" ]; then
            base_name=$(basename "$preview_file" .png)
            image_url="${pages_base_url}/pr-${{ inputs.pr-number }}/${base_name}.png"
            
            echo "<details>" >> $GITHUB_OUTPUT
            echo "<summary>ðŸŽ² <strong>${base_name}</strong> - Click to view preview</summary>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "![${base_name} preview](${image_url})" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "ðŸ“Ž [Download original file](${artifact_url}) | ðŸŒ [Direct image link](${image_url})" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "</details>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi
        done
        
        echo "" >> $GITHUB_OUTPUT
        echo "---" >> $GITHUB_OUTPUT
        echo "*Preview images generated automatically by GitHub Actions*" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'ðŸŽ² OpenSCAD Preview Images'
    
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github-token }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        body: ${{ steps.preview-comment.outputs.comment-body }}
        edit-mode: replace