name: 'Create PR Comment with Previews'
description: 'Create or update a PR comment with preview image links'
inputs:
  preview-files:
    description: 'Space-separated list of preview image files'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  github-token:
    description: 'GitHub token for commenting'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate preview comment body
      shell: bash
      id: preview-comment
      run: |
        echo "comment-body<<EOF" >> $GITHUB_OUTPUT
        echo "## 🎲 OpenSCAD Preview Images" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Generated preview images for this PR:" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        
        for preview_file in ${{ inputs.preview-files }}; do
          if [ -f "$preview_file" ]; then
            base_name=$(basename "$preview_file" .png)
            echo "### ${base_name}" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "📎 [Download ${base_name}.png](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi
        done
        
        echo "" >> $GITHUB_OUTPUT
        echo "---" >> $GITHUB_OUTPUT
        echo "*Preview images generated automatically by GitHub Actions*" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: 'github-actions[bot]'
        body-includes: '🎲 OpenSCAD Preview Images'
    
    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github-token }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        body: ${{ steps.preview-comment.outputs.comment-body }}
        edit-mode: replace