name: 'Generate Preview Images'
description: 'Generate high-quality preview images from all SCAD files'
outputs:
  preview-files:
    description: 'List of generated preview image files'
    value: ${{ steps.generate.outputs.preview-files }}
runs:
  using: 'composite'
  steps:
    - name: Find SCAD files
      shell: bash
      id: find-scad
      run: |
        find . -name "*.scad" -type f | head -20 > scad_files.txt
        echo "files<<EOF" >> $GITHUB_OUTPUT
        cat scad_files.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Generate preview images
      shell: bash
      id: generate
      run: |
        mkdir -p preview_output
        preview_files=""
        while IFS= read -r scad_file; do
          if [ -n "$scad_file" ]; then
            base_name=$(basename "$scad_file" .scad)
            preview_path="preview_output/${base_name}.png"
            echo "Generating preview: $scad_file -> $preview_path"
            xvfb-run -a openscad --render --imgsize=1024,1024 --colorscheme=Tomorrow --projection=p --camera=0,0,0,60,0,315,140 -o "$preview_path" "$scad_file"
            if [ -f "$preview_path" ]; then
              preview_files="$preview_files$preview_path "
            fi
          fi
        done < scad_files.txt
        echo "preview-files=$preview_files" >> $GITHUB_OUTPUT