name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run shellcheck on scripts
      uses: ./.github/actions/shellcheck

  pr-preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup OpenSCAD
      uses: ./.github/actions/setup-openscad
    
    - name: Generate preview images
      id: generate-previews
      uses: ./.github/actions/generate-previews
    
    - name: List generated files
      shell: bash
      id: list-files
      run: |
        if [ -d "preview_output" ] && [ "$(ls -A preview_output/*.png 2>/dev/null)" ]; then
          file_list=""
          for png_file in preview_output/*.png; do
            if [ -f "$png_file" ]; then
              base_name=$(basename "$png_file" .png)
              file_list="${file_list} ${base_name}"
            fi
          done
          echo "files=${file_list}" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload preview artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: openscad-previews-${{ github.event.pull_request.number }}
        path: preview_output/
        retention-days: 30
        if-no-files-found: ignore
    
    - name: Create PR comment with previews
      uses: ./.github/actions/pr-comment
      with:
        preview-files: ${{ steps.generate-previews.outputs.preview-files }}
        file-list: ${{ steps.list-files.outputs.files }}
        pr-number: ${{ github.event.pull_request.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}