name: 'Setup OpenSCAD'
description: 'Install OpenSCAD and dependencies for headless rendering'
runs:
  using: 'composite'
  steps:
    - name: Cache and install OpenSCAD packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openscad xvfb
        version: 1.0